### ISSUE TITLE
[Internal] Project Finalization: Blender Add-on Unification

### ISSUE THREAD

**Issue by regcs** [regcs/AliceLG#62]
To finish the [Blender Add-on Unification](https://github.com/regcs/AliceLG/projects/1) project, we need to do some final clean-up, update the Readme, merge the alicelg-2.0 branch into master, and release a new patch without "beta" status.

This should be done, after all other issues for Alice/LG 2.0 were resolved.

**Comment by regcs** [comment]
### Tasks for project finalization

- [ ] Final bug-fixes
- [ ] Clean up code
- [ ] Update Readme.md (include description of command line arguments, remove some old stuff, link to Bryan's tutorial, etc.)
- [ ] **Decide:** Officially do not support Blender versions < 2.93.6 to make sure live view color is always correct or support 2.93.0 to 2.93.5?
- [ ] Merge `alice-lg-2.0 branch` into 'master'
- [ ] Release patch version 2.0.4 as first non-experimental release of Alice/LG 2.0

**Comment by regcs** [comment]
Completed final maintenance tasks. The Blender Add-on Unification project is, therefore, finished.
